# -*- coding: utf-8 -*-
"""P&S_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F9CJBcRIKfvGy4dlCrg3QP3zwLEkHUfT
"""

from google.colab import drive
drive.mount('/content/gdrive')

cd gdrive/MyDrive/

import pandas as pd
import numpy as np
import math

df = pd.read_csv("15_daily_filtered_mean.csv")
df_feb = df[(df['Date'] >= '2021-02-01') & (df['Date'] <= '2021-02-28')]
df_mar = df[(df['Date'] >= '2021-03-01') & (df['Date'] <= '2021-03-31')]
df_feb = df_feb.loc[:, 'ND confirmed':]
df_mar = df_mar.loc[:, 'ND confirmed':]
print(df_mar)

"""One Sample  W-Test"""

feb_mean = df_feb.mean()
cols = len(df_feb.columns)
n = len(df_mar)

lambda_MLE = df_mar.sum().div(n)
se_MLE = df_mar.var().div(math.sqrt(n))

w = (lambda_MLE - feb_mean).div(se_MLE).abs()

print(w)
# alpha=0.05
reject_hypo = (w > 1.96)
print("1-Sample W-Test")
print("H0: mean(mar)=mean(feb), Reject:\n ", reject_hypo)
print("#######################################################################")

"""# **Results of Walds 1 sample testing for mean of cases and death**


Null hypothesis (H0):

the mean of daily cases and the mean of daily deaths for Feb’21 is different from the corresponding mean of daily values for March’21

Mean of Feb’21 cases/deaths **=** Mean of March’21 cases/deaths.


Alternate hypothesis(H1):

Mean of Feb’21 cases/deaths **not equal to** mean of March’21 cases/deaths.

Procedure :

We have taken the guess value as mean of daily values from Feb’21 cases/deaths and alpha = 0.05 as given in
documentation and the MLE estimator for mean of daily values from Mar’21 cases/deaths becomes the sample mean of daily values from Mar’21 cases/deaths.

Result:

walds 1 sample testing for mean of state ND confirmed cases is w=0.020000

walds 1 sample testing for mean of state NE confirmed cases is w=0.000110

walds 1 sample testing for mean of state ND deaths is w=0.867704

walds 1 sample testing for mean of state ND deaths is w=0.411946


which are less than z_alpha = 1.96 so accept the NULL hypothesis

One sample Z-Test
"""

# True Variance
df_t = df.loc[:, 'ND confirmed':]
mean = df.loc[:, 'ND confirmed':].mean()

diff_sum = df_t.sub(mean).sum()
True_Sample_Dev = diff_sum.mul(diff_sum).div(len(df_t) - 1) ** (1 / 2)
#
print("1-Sample Z-Test")
z = (df_mar.mean() - feb_mean).div(True_Sample_Dev.div(math.sqrt(n))).abs()
print(z)
reject_hypo = (z > 1.96)
print("H0: mean(mar)=mean(feb), Reject:\n ", reject_hypo)
print("#######################################################################")

"""# **Result of Z testing for mean of cases and death**

Null hypothesis (H0):

Mean of Feb’21 cases/deaths **=** Mean of March’21 cases/deaths.

Alternate hypothesis(H1):

Mean of Feb’21 cases/deaths **not equal to** mean of March’21 cases/deaths.

Result:

Z-sample testing for mean of state ND confirmed cases is w=2.334509e+13

Z-sample testing for mean of state NE confirmed cases is w=1.015164e+12

Z-sample testing for mean of state ND deaths is w=7.242974e+12

Z-sample testing for mean of state ND deaths is w=4.125351e+13

which are greater than z_alpha = 1.96 so reject the NULL hypothesis

One Sample T-test
"""

print("1-Sample T-test")

df_t = df_mar.loc[:, 'ND confirmed':]
mean = df_mar.loc[:, 'ND confirmed':].mean()

diff_sum = df_t.sub(mean).sum()
Sample_Dev = diff_sum.mul(diff_sum).div(len(df_t) - 1) ** (1 / 2)

t = (df_mar.mean() - feb_mean).div(Sample_Dev.div(math.sqrt(n))).abs()
print(t)

reject_hypo = (t > 2.04)
print("H0: mean(mar)=mean(feb), Reject:\n ", reject_hypo)
print("#######################################################################")
## Comment about applicability of tests

"""# **Result of T 1 sample testing for mean of cases and death**

Null hypothesis (H0):

Mean of Feb’21 cases/deaths **=** Mean of March’21 cases/deaths.

Alternate hypothesis(H1):

Mean of Feb’21 cases/deaths **not equal to** Mean of March’21 cases/deaths.


Procedure :

We have taken the alpha = 0.05,n = 30 as we took 30 days of data as given in documentation and calculated the
numerator and denominator of t.


Result:


As the calculated values for mean of state

ND confirmed cases = 3.594604e+16 

NE confirmed cases = 3.821252e+14

ND deaths       = 9.644333e+14

NE deaths       = 6.224550e+15

which are greater than t value 2.04 we are rejecting
the NULL hypothesis.

Two Sample Walds Test
"""

print("2-Sample Walds-test")
D_mean = df_feb.mean() - df_mar.mean()

Var_feb = ((df_feb - df_feb.mean()) ** 2).sum().div(len(df_feb))
Var_mar = ((df_mar - df_mar.mean()) ** 2).sum().div(len(df_mar))
std_dev = (Var_feb / len(df_feb) + Var_mar / len(df_mar)) ** 0.5

w = (D_mean / std_dev).abs()
print(w)
reject_hypo = (w > 1.96)

print("H0: mean(mar)=mean(feb), Reject:\n", reject_hypo)
print("#######################################################################")

"""# **Result of Walds 2 sample testing for mean of cases and death**

Null hypothesis (H0):

Mean of Feb’21 cases/deaths **=** Mean of March’21 cases/deaths.

Alternate hypothesis(H1):

Mean of Feb’21 cases/deaths **not equal to** Mean of March’21 cases/deaths.

Procedure :

We have taken the alpha = 0.05 as given in documentation and calculated the numerator and denominator of w.

Result:

As the w value for mean of state

ND confirmed cases    1.591266

NE confirmed  cases  0.036141

ND deaths       0.521922

NE deaths       1.723450

which are less than 1.96 we are rejecting the NULL hypothesis.

Two Sample Unpaired T-test
"""

print("2-Sample T-test")

Var_feb = ((df_feb - df_feb.mean()) ** 2).sum().div(len(df_feb) - 1)
Var_mar = ((df_mar - df_mar.mean()) ** 2).sum().div(len(df_mar) - 1)

pool_std = (Var_feb / len(df_feb) + Var_mar / len(df_mar)) ** 0.5

t = ((df_feb.mean() - df_mar.mean()) / pool_std).abs()
print(t)

reject_hypo = (t >= 2.0423)

print("H0: mean(mar)=mean(feb), Reject:\n", reject_hypo)
print("#######################################################################")

"""# **Result of T 2 sample unpaired testing for mean of cases and death**

Null hypothesis (H0):

Mean of Feb’21 cases/deaths **=** Mean of March’21 cases/deaths.

Alternate hypothesis(H1):

Mean of Feb’21 cases/deaths **not equal to** Mean of March’21 cases/deaths.

Procedure :

We have taken the alpha = 0.05 n=27, m=30 as given in documentation and calculated the numerator and denominator of t value.

Result:

As the t value for mean of state

ND confirmed cases    1.564428

NE confirmed  cases  0.035535

ND deaths       0.512856

NE deaths       1.693888


which are less than 2.0423 we are rejecting the NULL hypothesis.

# Applicability Of Tests

**Wald's Test**

In Wald's we need to have a Asymptomatically Normal estimator. Since N is fairly low, we cannot assume CLT applies in case of sample mean and hence this test is not applicable.

The above reasoning works well for 2 sample test as well, since we need both estimators to be Asymptomatically Normal. Hence this test is also not applicable.

**Z-test**

In Z-test, we need to have true standard deviation and either the N is large or the X is normally distributed. Since neither of the second requirement is true, we say the test is not applicable.

**T-test**

In one sample T-test, the requirement is that the data is normally distributed, since this is not the case and N is low as well. We say that the test is not applicable

In unpaired T-test, the required distributions should be independent and need to be normally distributed. In the current scenario, neither is the case so we say that the test is not applicable

In paired T-test, the difference distribution should be normally distributed but we cannot assume the same, hence we say that the test is not applicable
"""