# -*- coding: utf-8 -*-
"""Outlier_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i3vkiBjQZxzfrDoElcE5Z1BeYlFxybGI
"""


import pandas as pd
import numpy as np


def get_daily_counts(x):
  y=np.array([0])
  y=np.append(y,x)
  y=y[:-1]
  return x-y

def outliers_and_data_cleaning(x):
  Q1 = np.percentile(x, 25, interpolation = 'midpoint')
  Q3 = np.percentile(x, 75, interpolation = 'midpoint')
  IQR=Q3-Q1
  left=Q1-1.5*IQR
  right=Q3+1.5*IQR
  mean=np.mean(x)
  for i in range(x.size):
    if(x[i]<left and x[i]!=0):
      x[i]=mean
    elif(x[i]>right and x[i]!=0):
      x[i]=mean
  return x


def remove_outliers_and_create_new_file():
    dataframe = pd.read_csv('../15.csv')
    ne_confirmed = dataframe['NE confirmed'].to_numpy()
    nd_confirmed = dataframe['ND confirmed'].to_numpy()
    ne_deaths = dataframe['NE deaths'].to_numpy()
    nd_deaths = dataframe['ND deaths'].to_numpy()

    ne_confirmed_per_day = get_daily_counts(ne_confirmed)
    nd_confirmed_per_day = get_daily_counts(nd_confirmed)
    ne_deaths_per_day = get_daily_counts(ne_deaths)
    nd_deaths_per_day = get_daily_counts(nd_deaths)

    nd_confirmed_per_day = outliers_and_data_cleaning(nd_confirmed_per_day)
    ne_confirmed_per_day = outliers_and_data_cleaning(ne_confirmed_per_day)
    nd_deaths_per_day = outliers_and_data_cleaning(nd_deaths_per_day)
    ne_deaths_per_day = outliers_and_data_cleaning(ne_deaths_per_day)

    dataframe['ne_confirmed_per_day'] = ne_confirmed_per_day
    dataframe['nd_confirmed_per_day'] = nd_confirmed_per_day
    dataframe['ne_deaths_per_day'] = ne_deaths_per_day
    dataframe['nd_deaths_per_day'] = nd_deaths_per_day
    dataframe.to_csv('../15_updated.csv')



remove_outliers_and_create_new_file()

